services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - '5432:5432'
 
  core-api:
    build:
      dockerfile: docker/images/go/Dockerfile.core-api
    environment:
      - APP_NAME=${APP_NAME}
      - CORE_API_PORT=${CORE_API_PORT}
      - CORE_API_LISTEN_ADDRESS=${CORE_API_LISTEN_ADDRESS}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
      - WINDY_API_TOKEN=${WINDY_API_TOKEN}
      - IP_INFO_API_TOKEN=${IP_INFO_API_TOKEN}
    networks:
      - app-network

  vue:
    build:
      dockerfile: docker/images/vue/Dockerfile
    volumes:
      - './nivek-vue:/app'
    networks:
      - app-network

  nginx:
    ports:
      - '80:80'
      - '443:443'
    build:
      dockerfile: docker/images/nginx/Dockerfile
    volumes:
      - './nivek-vue:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - '~/certs/nivek.com.crt:/etc/ssl/certs/nivek.com.crt:ro'
      - '~/certs/nivek.com.key:/etc/ssl/private/nivek.com.key:ro'
    networks:
      - app-network

volumes:
  postgres_data:
    name: postgres_data

networks:
  app-network:
    driver: bridge
